### ISSUE TITLE
Pinta will not start on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by matswiklander** [MrCarroll/pinta-snap#12]
Installed Pinta with snap:
```
sudo snap install pinta
```

Tried to start pinta from command line and get the following errors:

```
Gtk-Message: 20:50:12.077: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
Segmentation fault (core dumped)
```

Checked that `/usr/share/X11/xkb` was present and it was.

Check the installed version of Pinta and snap reported:
```
pinta                      2.1.2                35     latest/stable    james-carroll✪  -
```

I'm using a english language installation with a swedish keyboard layout.

**Comment by JGCarroll** [comment]
Hi,

Could you try `sudo snap revert gnome-46-2404` in your terminal and trying again? The issue doesn't appear to be with Pinta itself, but elsewhere in the Snap ecosystem, which I've reported in the link above.

**Comment by matswiklander** [comment]
I tried and got the following response:
```
~$ sudo snap revert gnome-46-2404
error: cannot revert "gnome-46-2404": no revision to revert to
```

`snap list` reported the following:
```
gnome-42-2204              0+git.510a601        176    latest/stable/…  canonical✓      -
gnome-46-2404              0+git.18eace2        39     latest/stable    canonical✓      -
```

Should I specify a revision?

**Comment by JGCarroll** [comment]
It's a shame that didn't work as it would let you keep using the newer base distribution,

For an instant fix, assuming you have a previous copy of Pinta installed (from say last week), `sudo snap revert pinta` will cause it to use Gnome 42 over 46, which should sort you out.

Unfortunately you're actually on the same version of the runtime as I am, however I'm not experiencing an issue. As such there might not actually be anything to revert to, making this more curious.

**Comment by matswiklander** [comment]
I guess I have to be patient and wait for the problem to resolve in one way or the other.

Thank you for helping me out. Take care. :slightly_smiling_face:

**Comment by JGCarroll** [comment]
If the second revert didn't work, this one surely would;

```
sudo snap remove pinta --purge
sudo snap install pinta --revision 33
```

That way you'll grab last weeks package using Core22/Gnome42. It'd probably then be worth running
```
sudo snap refresh --hold=168h pinta
```

Which will prevent any upgrades for a week whilst this gets looked at (I imagine it'll take less than a week to revert any changes upstream).

**Comment by matswiklander** [comment]
Excellent! That solved the problem. :+1: 

Many thanks.

**Comment by JGCarroll** [comment]
I've reverted the Pinta snap on the store for the time being until the upstream issue is resolved. People should automatically start recovering from this, for Pinta.
